// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5oCbHX8GcQoeNzzkA2h416zWCpl1YKXk',
    appId: '1:754072927999:web:0b9ff6b7ff78702498d6ca',
    messagingSenderId: '754072927999',
    projectId: 'agendaconnect-8994f',
    authDomain: 'agendaconnect-8994f.firebaseapp.com',
    storageBucket: 'agendaconnect-8994f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7F18fqvKoyK16SgFabbW7WWmVFtIWZj8',
    appId: '1:754072927999:android:eeb58e0d03c010ef98d6ca',
    messagingSenderId: '754072927999',
    projectId: 'agendaconnect-8994f',
    storageBucket: 'agendaconnect-8994f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOBsC7OPn0TqhKAcjmABqaN3ZQyx3B24g',
    appId: '1:754072927999:ios:204564fb47ffb51698d6ca',
    messagingSenderId: '754072927999',
    projectId: 'agendaconnect-8994f',
    storageBucket: 'agendaconnect-8994f.appspot.com',
    iosBundleId: 'com.example.clientMeetingScheduler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOBsC7OPn0TqhKAcjmABqaN3ZQyx3B24g',
    appId: '1:754072927999:ios:204564fb47ffb51698d6ca',
    messagingSenderId: '754072927999',
    projectId: 'agendaconnect-8994f',
    storageBucket: 'agendaconnect-8994f.appspot.com',
    iosBundleId: 'com.example.clientMeetingScheduler',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5oCbHX8GcQoeNzzkA2h416zWCpl1YKXk',
    appId: '1:754072927999:web:455ca8acfdbfd1de98d6ca',
    messagingSenderId: '754072927999',
    projectId: 'agendaconnect-8994f',
    authDomain: 'agendaconnect-8994f.firebaseapp.com',
    storageBucket: 'agendaconnect-8994f.appspot.com',
  );
}
